events {}

http {
    map $http_first_nginx $set_first_header {
        ""      "true";
        default "false";
    }

    map $http_x_proxy_chain $already_proxied {
        "~$server_addr"  "true";
        default          "false";
    }
    upstream backend_servers {
        server nginx1:80;
        server nginx2:80;
        server nginx3:80;
        server app:8000;
    }
    log_format custom_headers '$remote_addr - $host '
                             '"X-Forwarded-For: $http_x_forwarded_for" ';
    access_log /dev/stdout custom_headers;

    server {
        listen 80;
        
        location / {
            set $target_upstream "backend_servers";

            if ($already_proxied = "true") {
                set $target_upstream "app:8000";
            }

            set $first_nginx "$http_first_nginx"; 
            set $x_forwarded_for $proxy_add_x_forwarded_for;

            if ($set_first_header = "true") {
                set $first_nginx "$server_addr";
                set $x_forwarded_for "$remote_addr";
            }
            proxy_set_header First-nginx "$first_nginx";
            proxy_set_header X-Forwarded-For $x_forwarded_for;
            
            proxy_pass http://$target_upstream;
        }
    }
}